export { default as Rect } from './Rectangle 17.svg?react';
export { default as DefaultProfileIc } from './defaultProfileIc.svg?react';
export { default as FooterInstaSvg } from './footerInstaSvg.svg?react';
export { default as FooterKakaoSvg } from './footerKakaoSvg.svg?react';
export { default as FooterLogoSvg } from './footerLogoSvg.svg?react';
export { default as FooterMailSvg } from './footerMailSvg.svg?react';
export { default as HeaderLogoSvg } from './headerLogoSvg.svg?react';
export { default as MakeGroupPlusBtn } from './mainMakeGroupBtnEnable.svg?react';
export { default as MakeGroupPlusHoverBtn } from './mainMakeGroupBtnHover.svg?react';
export { default as CheckboxIc } from './postDetailCheckIc.svg?react';
export { default as QuestionDefaultIc } from './questionDefaultIc.svg?react';
export { default as QuestioHoverIc } from './questionHoverIc.svg?react';
